## YAML Template.
---
georgia:
    voterFieldMap:
        CountyCode: s
        RegistrationNbr: s
        VoterStatus: l
        VoterLastName: L
        VoterFirstName: L
        VoterMiddleMaiden: L
        VoterNameSuffix: L
        VoterNameTitle: L
        ResHouseNbr: D
        ResStreetName: K
        ResStreetSuffix: K
        ResAptUnitNbr: L
        ResCityName: L
        ResZip: L
        ResZipPlus4: L
        MidrFlag: L
        PollWorker: L
        TransactionCode: L
        TransactionYearMonth: L
        Filler1: L
        DateOfBirth: L
        RegistrationDate: L
        Race: L
        Gender: L
        Absentee: L
        LandDistrict: L
        LandLot: L
        OriginalRegDate: L
        StatusReason: L
        Filler2: L
        CountyPrecinctId: L
        CityPrecinctId: L
        CongressionalDistrict: L
        SenateDistrict: L
        HouseDistrict: L
        JudicialDistrict: L
        CommDistrict: L
        SchoolDistrict: L
        CountyDistAName: L
        CountyDistAValue: L
        CountyDistBName: L
        CountyDistBValue: L
        MunicipalName: L
        MunicipalCode: L
        WardCityCouncilName: L
        WardCityCouncil: L
        CitySchoolDistName: L
        CitySchoolDist: L
        CityDistAName: L
        CityDistAValue: L
        CityDistBName: L
        CityDistBValue: L
        CityDistCName: L
        CityDistCValue: L
        CityDistDName: L
        CityDistDValue: L
        DateLastVotedDate: L
        TypeOfElection: L
        PartyLastVoted: L
        LastContactDate: L
        MailHouseNbr: L
        MailStreetName: L
        MailStreetSuffix: L
        MailAptUnitNbr: L
        MailCity: L
        MailState: L
        MailZip: L
        MailZipPlus4: L
        Filler3: L
        MailAddress2: L
        MailAddress3: L
        MailCounty: L
        DateAdded: L
        DateChanged: L
        DistrictCombo: L
        ResBuilding: L
        MailRRPOBox: L
        CombinedStreetAddr: L
        ExportDate: L
        
            