## YAML Template.
---
georgia:
    civicrmCountryID: 1228
    civicrmStateName: Georgia
    addressFieldMap:
        CombinedStreetAddr: street_address
        ResHouseNbr: street_number
        ResStreetName: street_name
        ResStreetSuffix: street_type
        ResAptUnitNbr: street_unit
        ResCityName: city
        ResZip: postal_code
        ResZipPlus4: postal_code_suffix
    voterGenderField: Gender
    voterCountyCodeField: CountyCode
    civicrmTable: civicrm_value_georgia_voter_registration_2
    voterIDfield: RegistrationNbr
    voterFieldMap:
        CountyCode: registered_county_40
        RegistrationNbr: ga_voter_id_2
        VoterStatus: voter_status_42
        VoterLastName: last_name_43
        VoterFirstName: first_name_44
        VoterMiddleMaiden: middle_maiden_name_45
        VoterNameSuffix: name_suffix_46
        VoterNameTitle: name_prefix_47
        ResHouseNbr: residence_house_number_48
        ResStreetName: residence_street_name_49
        ResStreetSuffix: residence_street_suffix_50
        ResAptUnitNbr: residence_apartment_unit_number_51
        ResCityName: residence_city_name_52
        ResZip: residence_zipcode_53
        ResZipPlus4: residence_zipcode_plus_4_54
        MidrFlag: mail_in_id_required_55
        PollWorker: poll_worker_56
        TransactionCode: transaction_code_57
        TransactionYearMonth: transaction_date_58
        Filler1: filler_1_59
        DateOfBirth: date_of_birth_60
        RegistrationDate: registration_date_61
        Race: race_62
        Gender: gender_63
        Absentee: absentee_voter_64
        LandDistrict: land_district_65
        LandLot: land_lot_66
        OriginalRegDate: original_registration_date_67
        StatusReason: status_reason_68
        Filler2: filler_2_69
        CountyPrecinctId: county_precinct_id_70
        CityPrecinctId: city_precinct_id_71
        CongressionalDistrict: congressional_district_72
        SenateDistrict: senate_district_73
        HouseDistrict: house_district_74
        JudicialDistrict: judicial_district_75
        CommDistrict: county_commission_district_76
        SchoolDistrict: school_district_77
        CountyDistAName: county_district_a_name_78
        CountyDistAValue: county_district_a_value_79
        CountyDistBName: county_district_b_name_80
        CountyDistBValue: county_district_b_value_81
        MunicipalName: municipal_name_82
        MunicipalCode: municipal_code_83
        WardCityCouncilName: ward_city_council_name_84
        WardCityCouncil: ward_city_council_85
        CitySchoolDistName: city_school_district_name_86
        CitySchoolDist: city_school_district_87
        CityDistAName: city_district_a_name_88
        CityDistAValue: city_district_a_value_89
        CityDistBName: city_district_b_name_90
        CityDistBValue: city_district_b_value_91
        CityDistCName: city_district_c_name_92
        CityDistCValue: city_district_c_value_93
        CityDistDName: city_district_d_name_94
        CityDistDValue: city_district_d_value_95
        DateLastVotedDate: date_last_voted_96
        TypeOfElection: type_of_election_97
        PartyLastVoted: party_last_voted_98
        LastContactDate: last_contact_date_99
        MailHouseNbr: mailing_address_house_number_100
        MailStreetName: mailing_address_street_name_101
        MailStreetSuffix: mailing_address_street_suffix_102
        MailAptUnitNbr: mailing_address_apartment_unit_n_103
        MailCity: mailing_address_city_104
        MailState: mailing_address_state_105
        MailZip: mailing_address_zipcode_106
        MailZipPlus4: mailing_address_zip_plus_4_110
        Filler3: filler_3_121
        MailAddress2: mailing_address_second_line_111
        MailAddress3: mailing_address_third_line_112
        MailCounty: mailing_address_country_113
        DateAdded: date_record_added_114
        DateChanged: date_record_changed_115
        DistrictCombo: district_combo_116
        ResBuilding: residence_building_designation_117
        MailRRPOBox: mailing_address_rural_route_po_b_118
        CombinedStreetAddr: combined_street_address_119
        ExportDate: export_date_120 
            